### ISSUE TITLE
strider successfully executed, but sent failed to bitbucket

### ISSUE THREAD

**Issue by wq7** [Strider-CD/strider-bitbucket#37] opened 2016-06-28 03:00 UTC
I'm sorry, asked once again.

The error on the pull request comment  and also commits is error.
This is build success of strider:

![2016-06-28 10-27-40](https://cloud.githubusercontent.com/assets/12848296/16402398/da73f8ac-3d1e-11e6-9f17-a1f7f7583fc5.png)

but, it is faild on bitbucket:
![2016-06-28 10-28-37](https://cloud.githubusercontent.com/assets/12848296/16402415/f0e1c8bc-3d1e-11e6-8dc2-0482292525b2.png)

![2016-06-28 10-28-09](https://cloud.githubusercontent.com/assets/12848296/16402420/fa8f1194-3d1e-11e6-9a11-8713a0e04f86.png)

**Comment by knownasilya** [comment] 2016-06-28 12:45
If you click(or hover over it) on that failed link in bitbucket, do you get more details about what the issue is?

**Comment by stevenbool** [comment] 2016-06-29 09:14
@knownasilya  The code is correct,strider build success, but strider send failed message to bitbucket when strider build completed. 
strider build success: 
![_2016-06-29_17-02](https://cloud.githubusercontent.com/assets/12848296/16446964/d26fad78-3e1c-11e6-801a-07ebaa3ac3e7.png)
on bitbucket:
![_2016-06-29_17-06](https://cloud.githubusercontent.com/assets/12848296/16446999/e62c36a6-3e1c-11e6-8766-ae06fadcd691.png)

**Comment by oliversalzburg** [comment] 2016-06-29 09:53
The status reporting isn't part of strider-bitbucket, is it? Seems like this would be an issue with strider-webhooks, isn't it?

**Comment by knownasilya** [comment] 2016-06-29 13:06
See https://github.com/Strider-CD/strider-bitbucket/pull/27

@nomean42 any thoughts here?

**Comment by nomean42** [comment] 2016-06-30 04:16
I got fix for this, but i don't have enough time. The best way is make this fix after [refactor](https://github.com/Strider-CD/strider-bitbucket/pull/31)

**Comment by ramirost** [comment] 2016-08-12 10:24
We can reproduce this problem every time we run a job that does not execute the deploy phase.

I provided PR #41 fixing this on master. 

I also attach a [patch](https://github.com/Strider-CD/strider-bitbucket/files/415102/patch.diff.txt) that can be applied on version 1.4.2 which is the one we are using right now

**Closed** 2020-06-16 02:54 UTC
Labels: bug, needs investigation

**Comment by knownasilya** [comment] 2020-06-16 12:40
Thanks for closing, this was fixed.
